name: LLMHealthFramingEffect
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.4
  - jupyterlab
  - matplotlib
  - seaborn
  - jinja2==3.1.6
  - conda-forge::anthropic
  - conda-forge::openai
  - conda-forge::python-dotenv
  - conda-forge::pandas
  - conda-forge::google-genai
  - main::google-cloud-storage
  - main::gcsfs
  - pip:
    - torch
    - torchvision
    - accelerate
    - transformers
    - biopython
    - sentence-transformers
    - textstat
    - spacy