from utils import load_json_file, save_dataset_to_json
import json
import spacy
import re
from transformers import pipeline
from sentence_transformers import SentenceTransformer, util
import textstat
from tqdm import tqdm
import argparse
import os

class Evaluator:
    def __init__(self):
        print("Loading models (this may take a minute on first run)...")
        # 1. High-accuracy Sentiment Model (SiEBERT)
        self.sentiment_pipe = pipeline(
            "sentiment-analysis", 
            model="siebert/sentiment-roberta-large-english"
        )
        
        # 2. Semantic Similarity Model
        self.semantic_model = SentenceTransformer('all-MiniLM-L6-v2')
        
        # 3. NLP for Entities
        self.nlp = spacy.load("en_core_web_sm")
        
        self.hedge_words = self.load_hedgesload_hedges()

    def load_hedges(self):
        lines = []

        with open('../data/hedges_data.txt', 'r') as file:
            for line in file:
                clean_line = line.strip()
                
                # Check if line is empty OR starts with %
                if not clean_line or clean_line.startswith('%'):
                    continue
                    
                lines.append(clean_line)
        return lines

    def get_entities(self, text):
        doc = self.nlp(text)
        return set([ent.text.lower() for ent in doc.ents])

    def get_roberta_sentiment(self, text):
        """Returns the label and confidence score from SiEBERT."""
        result = self.sentiment_pipe(text[:512])[0]  # Truncated to 512 for RoBERTa limits
        return {
            "label": result['label'],
            "confidence": round(result['score'], 4)
        }

    def count_hedging(data: list):
        import collections

        # Replace this list with the one generated by the AI
        hedges_found = data
        hedges_found = ["might", "suggests", "possibly", "might", "could", "it seems that"]

        # 1. Calculate the absolute total
        total_count = len(hedges_found)

        # 2. Calculate frequency of each specific hedge
        frequency = collections.Counter(hedges_found)

        print(f"Total Hedges Found: {total_count}")
        print("Frequency Breakdown:")
        for hedge, count in frequency.items():
            print(f"- {hedge}: {count}")

    def evaluate_pair(self, text_a, text_b):
        # Semantic Similarity
        emb1 = self.semantic_model.encode(text_a, convert_to_tensor=True)
        emb2 = self.semantic_model.encode(text_b, convert_to_tensor=True)
        sem_sim = util.pytorch_cos_sim(emb1, emb2).item()

        # Entity Overlap
        ent_a = self.get_entities(text_a)
        ent_b = self.get_entities(text_b)
        intersection = ent_a.intersection(ent_b)
        ne_overlap = len(intersection) / len(ent_a.union(ent_b)) if ent_a.union(ent_b) else 1.0

        # Lexical Stats
        def get_stats(text):
            sent = self.get_roberta_sentiment(text)
            hedges = sum(1 for w in self.hedge_words if re.search(r'\b' + w + r'\b', text.lower()))
            return {
                "sentiment": sent['label'],
                "sentiment_confidence": sent['confidence'],
                "hedge_count": hedges,
                "reading_ease": textstat.flesch_reading_ease(text),
                "length_words": len(text.split())
            }

        return {
            "comparison": {
                "semantic_similarity": f"{sem_sim:.2%}",
                "entity_overlap": f"{ne_overlap:.2%}",
                "common_entities": list(intersection)
            },
            "response_positive_metrics": get_stats(text_a),
            "response_negative_metrics": get_stats(text_b)
        }

    # TODO: would need to change the code to fit the actual things we need
    def process_batch(self, input_data):
        results = {}
        for uid, pairs in tqdm(input_data.items(), desc="Processing Items"):
            category = uid.split("_")[1]
            # if category == "multiturn":
            #     continue
            # print(f"Analyzing {uid}...")
            results[uid] = self.evaluate_pair(pairs['positive_answer'], pairs['negative_answer'])
        return results

# def format_outputs(raw_data):
#     grouped = {}
    
#     for item in raw_data:
#         cid = item["custom_id"]
#         text = item["output_text"]
            
#         key = cid.split("-")[1]
#         parts = key.split("_")
        
#         # The last part is the sentiment (positive/negative)
#         sentiment = parts[-1]
        
#         # e.g., "CD002818_effectiveness1"
#         pair_key = "_".join(parts[:-1])

#         if pair_key not in grouped:
#             grouped[pair_key] = {}

#         if sentiment == "positive":
#             grouped[pair_key]["positive_answer"] = text
#         elif sentiment == "negative":
#             grouped[pair_key]["negative_answer"] = text
            
#     return grouped

def format_outputs(raw_data: list[dict]) -> dict:
    grouped = {}
    
    for item in raw_data:
        review_id = item["ReviewID"]
        q_and_a = item["ModelGeneratedAnswersWithQuestions"]

        for k, v in q_and_a.items():
            if k != "multiturn":
                pair_key = f"{review_id}_{k}"
                if pair_key not in grouped:
                    grouped[pair_key] = {}
                grouped[pair_key]["positive_answer"] = v["positive_answer"]
                grouped[pair_key]["negative_answer"] = v["negative_answer"]
            else: # multiturn situation
                pos_answers = v["positive_answer"]
                neg_answers = v["negative_answer"]
                pair_key = f"{review_id}_{k}"
                for index, item in enumerate(list(zip(pos_answers, neg_answers))):
                    pair_key = f"{pair_key}_{index}"
                    if pair_key not in grouped:
                        grouped[pair_key] = {}
                    grouped[pair_key]["positive_answer"] = item[0]
                    grouped[pair_key]["negative_answer"] = item[1]

    return grouped

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Running Lexical Analysis")

    parser.add_argument("--file_path", default="./inputs", help="path to the file with outputs to analzye")
    parser.add_argument("--output_path", default="./outputs", help="path/file name of where the results should be saved.")
    
    args = parser.parse_args()

    file_path = args.file_path
    output_path = args.output_path

    print()
    print("Arguments Provided for Evaluation:")
    print(f"File Path:        {file_path}")
    print(f"Output Path:       {output_path}")
    print()

    data = load_json_file(file_path)
    formatted_data = format_outputs(data)

    # Run
    evaluator = Evaluator()
    final_report = evaluator.process_batch(formatted_data)

    print("\n--- FINAL EVALUATION REPORT ---")
    print(json.dumps(final_report, indent=2))

    # Save to file
    save_dataset_to_json(final_report, output_path, jsonl=False)
